# Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# system deps for psycopg2 and libmagic
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libmagic1 \
    curl \
 && rm -rf /var/lib/apt/lists/*

# copy requirements first (caches)
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY . /app/

# make entrypoint executable
RUN chmod +x /app/entrypoint.sh

ENV PATH="/root/.local/bin:${PATH}"

EXPOSE 8000

CMD ["/app/entrypoint.sh"]
